notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/Statwolf/statwolf-new-component-plugin/master/travis_installer.sh | sh'

git:
  depth: 10

sudo: false

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES=""

before_install:
  - npm_config_registry=http://git.statwolf.com:5984 npm install

matrix:
  - ATOM_CHANNEL=stable
  - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
      - build-essential
      - git
      - libgnome-keyring-dev
      - fakeroot
